### ISSUE TITLE
是否可以根据 配置文件是否有相应配置来建立 bean

### ISSUE THREAD

**Issue by coolyu0916** [LianjiaTech/retrofit-spring-boot-starter#72]
@RetrofitClient(baseUrl = "${test.baseUrl}")
public interface HttpApi {

    @GET("person")
    Result<Person> getPerson(@Query("id") Long id);
}
如果yml中没有test.baseUrl 能否不创建bean，而是提示一个警告？
或者用@conditionalonproperty 来作判断？

或者 baseURL 支持 SpEL?

**Comment by chentianming11** [comment]
不清楚什么场景会出现这种情况。我个人觉得没有配置算是很严重的问题，所以倾向于启动时提前暴露问题。

**Comment by chentianming11** [comment]
@conditionalonproperty 可以考虑支持

**Comment by coolyu0916** [comment]
场景是我想将一些经常用的API封装成自己的starter方便引入调用，但是这些API不是每个应用都需要用到，所以想通过是否经过了配置来决定是否生成bean。已经自定义重写了 AutoConfiguredRetrofitScannerRegistrar 和 ClassPathRetrofitClientScanner 来解决了这个问题，但是编码有些硬，想知道有没有更好的方法。

**Comment by chentianming11** [comment]
***@***.***来支持吧。如果有这个注解，属性不存在就不加载。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LianjiaTech/retrofit-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LianjiaTech/retrofit-spring-boot-starter] 是否可以根据 配置文件是否有相应配置来建立 bean (#72)





 
场景是我想将一些经常用的API封装成自己的starter方便引入调用，但是这些API不是每个应用都需要用到，所以想通过是否经过了配置来决定是否生成bean。已经自定义重写了 AutoConfiguredRetrofitScannerRegistrar 和 ClassPathRetrofitClientScanner 来解决了这个问题，但是编码有些硬，想知道有没有更好的方法。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
